# Zameni sa vrednostima iz SonarCloud-a (Information stranica projekta)
sonar.organization=ORG_KEY
sonar.projectKey=ORG_KEY_sonar-sql-demo
sonar.projectName=sonar-sql-demo

sonar.sources=sql
sonar.sourceEncoding=UTF-8

# Po defaultu Sonar .sql fajlove tretira kao PL/SQL (Oracle).
# Ovim kažemo da su .sql fajlovi T-SQL (SQL Server).
sonar.tsql.file.suffixes=.sql,.tsql
sonar.plsql.file.suffixes=.pks,.pkb
